"""Deterministic LLMProvider for tests and for running the stack without an API key."""

import json
from collections.abc import Sequence

from app.application.ports.llm.llm_provider import LLMRequest, LLMResponse

DEFAULT_FAKE_CODE = '''\
"""Placeholder produced by FakeLLMProvider (no real LLM was called)."""

from sqlalchemy import text
from sqlalchemy.ext.asyncio import AsyncConnection


async def modernized_routine(conn: AsyncConnection) -> None:
    await conn.execute(text("SELECT 1"))
'''

DEFAULT_FAKE_RESPONSE = json.dumps(
    {
        "python_code": DEFAULT_FAKE_CODE,
        "strategy": "hybrid",
        "architectural_decisions": [
            {
                "topic": "provider",
                "decision": "Fake provider output",
                "rationale": "LLM_PROVIDER=fake; configure a real provider for translations.",
            }
        ],
        "warnings": ["Generated by FakeLLMProvider: this is not a real translation."],
    }
)


class FakeLLMProvider:
    """Returns scripted responses in order (the last one repeats) or raises `error`.

    Every request is recorded in `requests` so tests can assert on the prompt.
    """

    def __init__(
        self,
        responses: Sequence[str] = (DEFAULT_FAKE_RESPONSE,),
        *,
        error: Exception | None = None,
        model: str = "fake-model",
    ) -> None:
        if not responses:
            raise ValueError("FakeLLMProvider needs at least one response")
        self._responses = list(responses)
        self._error = error
        self._model = model
        self.requests: list[LLMRequest] = []

    async def generate(self, request: LLMRequest) -> LLMResponse:
        self.requests.append(request)
        if self._error is not None:
            raise self._error
        index = min(len(self.requests), len(self._responses)) - 1
        content = self._responses[index]
        return LLMResponse(
            content=content,
            provider="fake",
            model=self._model,
            input_tokens=len(request.system_prompt + request.user_prompt) // 4,
            output_tokens=len(content) // 4,
            latency_ms=0.0,
            finish_reason="stop",
        )
